source 'https://cdn.cocoapods.org/

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

abstract_target 'Coherence' do
    pod "Coherence", :path => "../"
    pod "TraceLog", "~> 5.0.0-beta.2"
    
    target 'Coherence Example' do
        platform :ios, '9.0'
    end

    target 'iOS Test Host' do
        platform :ios, '9.0'

        target 'iOS Tests'
    end

    target 'OSX Test Host' do
        platform :osx, '10.13'

        target 'OSX Tests'
    end

    target 'tvOS Test Host' do
        platform :tvos, '9.0'

        target 'tvOS Tests'
    end

    target 'watchOS Test App Extension' do
        platform :watchos, '2.0'
    end
end
