source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Coherence' do
  pod "Coherence", :path => "../"
  pod "Coherence/Connect", :path => "../"
end

target 'Tests' do
  pod "Coherence", :path => "../"
  pod "Coherence/Connect", :path => "../"
end
