language: generic


git:
  submodules: false

env:
  global:
    - WORKSPACE=Example/Coherence.xcworkspace

podfile: Example/Podfile

matrix:
  include:
    -
      os: osx
      osx_image: xcode10.2
      env: 
         - BUILD="pod lint"
    - 
      os: osx
      osx_image: xcode10.2
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=12.2,name=iPhone Xs"
         - SCHEME="iOS Test Host"
         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode10.2
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6"
#         - SCHEME="iOS Test Host"
#         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode10.2
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=9.2,name=iPhone 5s"
#         - SCHEME="iOS Test Host"
#         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode9.3
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=8.1,name=iPhone 6"
#         - SCHEME="iOS Test Host"
#         - ACTION="-enableCodeCoverage YES test"
    -
      os: osx
      osx_image: xcode10.2
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=OS X,arch=x86_64"
         - SCHEME="OSX Test Host"
         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode10.2
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=tvOS Simulator,OS=9.0,name=Apple TV 1080p"
#         - SCHEME="tvOS Test Host"
#         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode10.2
#     env:
#         - BUILD="xcodebuild"
#        - TEST_DEST="platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p"
#         - SCHEME="tvOS Test Host"
#         - ACTION="-enableCodeCoverage YES test"
#    -
#      os: osx
#      osx_image: xcode10.2
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=10.3.1,name=iPhone 6s"
#         - SCHEME="watchOS Test App"
#         - ACTION=build

before_install:
  # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
  - rvm get head --auto-dotfiles || true

install:
  #
  # If there is a Gemfile for this os, install bundler and ask bundler to install the gems
  #
  - |
    if [ -e Gemfile ]; then
       export BUNDLE_GEMFILE=Gemfile
       gem install bundler
       bundler install
       bundler exec pod repo update
       pushd Example
       bundler exec pod install
       popd
    fi

script:
  - |
    if [[ "$BUILD" == "swift build"  ]]; then
      set -e  # Fail (and stop build) on first non zero exit code
      swift test
      set +e
    fi
  - |
    if [[ "$BUILD" == "pod lint" ]]; then
        set -e  # Fail (and stop build) on first non zero exit code
        bundler exec pod repo update
        bundler exec pod lib lint
        set +e
    fi
  - |
    if [[ "$BUILD" == "xcodebuild"  ]]; then
        set -eo pipefail
        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" $ACTION | bundler exec xcpretty
        set +eo pipefail
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
