<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by Tony Stone (Mobile Grid, Inc.) -->
<wsdl:description targetNamespace="http://new.webservice.namespace" xmlns:wsdl="http://www.w3.org/ns/wsdl" xmlns:wsoap="http://www.w3.org/ns/wsdl/soap" xmlns:whttp="http://www.w3.org/ns/wsdl/http" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://new.webservice.namespace">
	<wsdl:types>
		<xs:schema targetNamespace="http://new.webservice.namespace" elementFormDefault="qualified">
			<xs:element name="NewMessageRequest" type="xs:string"/>
			<xs:element name="NewMessageResponse" type="xs:string"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:interface name="DataCenterInterface">
		<wsdl:operation name="List" pattern="http://www.w3.org/ns/wsdl/in-out">
			<wsdl:input/>
			<wsdl:output/>
		</wsdl:operation>
		<wsdl:operation name="Read" pattern="http://www.w3.org/ns/wsdl/in-out">
			<wsdl:input/>
			<wsdl:output/>
		</wsdl:operation>
	</wsdl:interface>
	<wsdl:binding name="DataCenterHTTPBinding" interface="tns:DataCenterInterface" type="http://www.w3.org/ns/wsdl/http">
		<wsdl:operation ref="tns:List">
			<wsdl:input/>
			<wsdl:output/>
		</wsdl:operation>
		<wsdl:operation ref="tns:Read">
			<wsdl:input/>
			<wsdl:output/>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DataCenterService" interface="tns:DataCenterInterface">
		<wsdl:endpoint name="DataCenterEndPoint" binding="tns:DataCenterHTTPBinding" address="https://my.rightscale.com/api/clouds/:cloud_id"/>
	</wsdl:service>
</wsdl:description>
